auto: true


locales:
  en:
    stylesheet_dir: stylesheets
    javascript_dir: javascripts
    image_dir: /images
    translation: translation
    reviewing: reviewing
    proofreading: proofreading
    transcription: transcription
    home: home
    services: services
    contact: contact
    about: about
    slogan: I'm working as freelance translator since 2008 from various Romance languages and English to Italian.
    contact_intro: Feel free to contact me or to connect through the following channels
    fields_of_specialization: fields of specialization 
    commercials: Commercials
    commerce: Commerce
    economics_and_finance: Economics and Finance
    law_and_legal: Law and Legal
    it_and_web_content: IT and Web content
    public_sector: Public Sector
    civil_and_mechanical_engineering: Civil and Mechanical Engineering
    transport: Transport
    journalism: Journalism
    tourism_and_travel: Tourism and Travel
    fashion_and_apparel: Fashion and Apparel
    food_and_oenology: Food and Oenology
    culinary_arts: Culinary Arts
    literature: literature

    types_of_translations: Types of translations
    company_letters: Company letters
    minutes_of_meetings: Minutes of Meetings
    business_contracts: Business contracts
    by_laws: By-laws and Articles of Associations
    company_brochures: Company brochures
    touristic_brochures_and_websites: Touristic brochures and websites
    marketing_campain_scripts: Marketing campaign scripts
    certificates_and_letters_of_request: Certificates and letters of request
    articles_and_press_releases: Articles and press releases
    industrial_automation_technical_manuals: Industrial automation technical manuals
    user_manuals_and_installation_instructions: User Manuals and Installation Instructions
    product_data_sheets: Product Data Sheets
    novels_and_comic_books: Novels and comic books
  it:
    stylesheet_dir: ../stylesheets
    javascript_dir: ../javascripts
    image_dir: ../images
    translation: traduzione
    reviewing: revisione
    proofreading: proofreading
    transcription: trascrizione
    home: home
    services: servizi
    contact: contatti
    about: chi sono 
    slogan: Dal 2008 lavoro come traduttrice indipendente da varie lingue romanze e dall'inglese verso l'italiano.
    contact_intro: Sarò lieta di rispondere alle richieste di contatto attraverso i seguenti canali 
    fields_of_specialization: Ambiti di specializzazione 
    commercials: Annunci pubblicitari
    commerce: Commerciale
    economics_and_finance: Economico e finanziario
    law_and_legal: Legale
    it_and_web_content: IT e contenuti Web
    public_sector: Appalti
    civil_and_mechanical_engineering: Ingegneria civie e meccanica
    transport: Trasporti
    journalism: Giornalismo
    tourism_and_travel: Viaggi e turismo
    fashion_and_apparel: Moda e accessori
    food_and_oenology: Enogastronomia
    culinary_arts: Culinaria e Ricette 
    literature: Letterario 

    types_of_translations: Tipi di traduzione
    company_letters: Lettere commerciali
    minutes_of_meetings: Verbali di riunioni d'affari
    business_contracts: Contratti commerciali
    by_laws: Statuti societari e associativi
    company_brochures: Presentazioni e brochure aziendali
    touristic_brochures_and_websites: Brochure e depliant turistici, siti turistici e di viaggio 
    marketing_campain_scripts: Testi per campagne di marketing
    certificates_and_letters_of_request: Certificati, moduli di richiesta, autocertificazioni, diplomi e CV
    articles_and_press_releases: Articoli e comunicati stampa
    industrial_automation_technical_manuals: Automazione industriale, manuali tecnici per macchinari industriali 
    user_manuals_and_installation_instructions: Manuali di istruzioni e di installazione
    product_data_sheets: Schede prodotto
    novels_and_comic_books: Romanzi e fumetti
